apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: product-infrastructure
  title: Product infrastructure template
  description: Product infrastructure template, allows creating app insights, and Azure Key Vault.
  tags:
    - terraform
  links:
    - url: https://hmcts-reform.slack.com/app_redirect?channel=cloud-native
      title: cloud-native on Slack
      icon: chat
spec:
  owner: dts_platform_operations
  type: service
  templater: cookiecutter
  parameters:
    - title: Provide some simple information
      required:
        - component_id
        - owner
        - slack_contact_channel
      properties:
        component_id:
          title: Product
          type: string
          description: Product this component belongs to, normally the team name, e.g. cmc
        slack_contact_channel:
          title: Slack contact channel
          type: string
          description: Which channel (or user) to contact if there's any issues with this service.
        description:
          title: Description
          type: string
          description: Description of the application, a sensible default will be used if not specified.
        github_admin_team:
          title: GitHub admin team
          type: string
          description: Which GitHub team should have admin permissions?
        enable_app_insights:
          title: Add application insights
          type: boolean
          default: true
          description: We use application insights for logging, do you want to deploy it?
        enable_key_vault:
          title: Add Azure Key Vault
          type: boolean
          description: Azure Key Vault is used for storing secrets, do you want to deploy it?
        aad_group_name:
          title: Azure AD team group
          type: string
          description: (Optional, required if deploying a key vault), Your teams Azure AD group name.
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group
    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com

  steps:
    - id: template
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./skeleton
        values:
          product: '${{ parameters.component_id }}'
          description: '${{ parameters.description }}'
          enable_app_insights: '${{ parameters.enable_app_insights }}'
          enable_key_vault: '${{ parameters.enable_key_vault }}'
          aad_group_name: '${{ parameters.aad_group_name }}'
          owner: '${{ parameters.owner }}'
          destination: '${{ parameters.repoUrl | parseRepoUrl }}'
          slack_contact_channel: ${{ parameters.slack_contact_channel }}
    - id: publish
      name: Publish
      action: publish:github
      input:
        allowedHosts: ['github.com']
        description: This is ${{ parameters.name }}
        repoUrl: ${{ parameters.repoUrl }}
        access: ${{ parameters.github_admin_team }}
        requireCodeOwnerReviews: true
        repoVisibility: public
        topics:
          - ${{ parameters.component_id }}
    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: '${{ steps.publish.output.repoContentsUrl }}'
        catalogInfoPath: '/catalog-info.yaml'
  output:
    remoteUrl: '${{ steps.publish.output.remoteUrl }}'
    entityRef: '${{ steps.register.output.entityRef }}'
