apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "${{ values.product }}-product-infrastructure"
  description: ${{ values.description }}
  annotations:
    # This must match folder-name/job-name in Jenkins.
    jenkins.io/github-folder: 'HMCTS_${{ values.product }}/${{ values.product }}-product-infrastructure'
    github.com/project-slug: '${{ values.destination.owner }}/${{ values.destination.repo }}'
  tags:
    - terraform
  links:
    - url: https://hmcts-reform.slack.com/app_redirect?channel=${{ values.slack_contact_channel }}
      title: ${{ values.slack_contact_channel }} on Slack
      icon: chat
spec:
  type: service
  lifecycle: experimental
  owner: ${{ values.owner }}
  