apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "{{ cookiecutter.product }}-product-infrastructure"
  description: {{ cookiecutter.description }}
  annotations:
    # This must match folder-name/job-name in Jenkins.
    jenkins.io/github-folder: 'HMCTS_{{ cookiecutter.product }}/{{ cookiecutter.product }}-product-infrastructure'
    github.com/project-slug: '{{ cookiecutter.storePath }}'
  tags:
    - shared-infra
    - {{ cookiecutter.product }}
spec:
  type: service
  lifecycle: experimental
  owner: {{ cookiecutter.owner }}
